# Generated by Django 5.2.4 on 2025-07-25 06:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Mt Kenya 3-day', max_length=250)),
                ('slug', models.SlugField(help_text='A short label for URLs, mount-kenya-3-day', unique=True)),
                ('duration_days', models.IntegerField(help_text='Number of days for the expedition')),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('challenging', 'Challenging'), ('strenuous', 'Strenuous')], default='moderate', max_length=50)),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(help_text='Detailed description of the expedition')),
                ('itinerary', models.TextField(help_text='Day-by-day breakdown of the trek')),
                ('included_services', models.TextField(blank=True, help_text="What's included ( guides, food, park fees)", null=True)),
                ('excluded_services', models.TextField(blank=True, help_text="What's excluded", null=True)),
                ('max_participants', models.IntegerField(default=15)),
                ('min_participants', models.IntegerField(default=5)),
                ('is_active', models.BooleanField(default=True, help_text='Is this expedition currently open for bookings?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpeditionDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('current_bookings', models.IntegerField(default=0)),
                ('is_fully_booked', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_dates', to='expeditions.expedition')),
            ],
            options={
                'unique_together': {('expedition', 'start_date')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('num_participants', models.IntegerField()),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=50)),
                ('payment_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_gateway_response', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, help_text='Optional: User who made the booking if logged in', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('expedition_date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='expeditions.expeditiondate')),
            ],
            options={
                'ordering': ['-booking_date'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('dietary_restrictions', models.TextField(blank=True, null=True)),
                ('medical_conditions', models.TextField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='expeditions.booking')),
            ],
        ),
    ]
