# Generated by Django 5.2.4 on 2025-08-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expeditions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedition',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='expedition_images/'),
        ),
    ]
