# Generated by Django 5.2.4 on 2025-08-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expeditions', '0002_expedition_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedition',
            name='dates',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
